### PR TITLE
Bug 1798166 - Fix color contrast to be compliant with WCAG AA 2.0

### PR DESCRIPTION
**Pull request by dannycolin**
#### Details

This PR fixes color contrast to be compliant with WCAG AA 2.0

#### Additional info
* [bmo#1798166](https://bugzilla.mozilla.org/show_bug.cgi?id=1798166)

#### Test Plan

I ran the devtools accessibility tools on the different pages.

### CODE REVIEW

**Comment by justdave** [comment]
Did you forget to add some files to your commit?  This looks like it's adding two new css files, but there's no changes to templates or other css files to make them load the new files.

**Comment by dannycolin** [comment]
> Did you forget to add some files to your commit? This looks like it's adding two new css files, but there's no changes to templates or other css files to make them load the new files.

I didn't had to add this files in any template for them to be applied locally.

**Comment by justdave** [comment]
Is it dynamically looking for one that matches the name of the template if it exists? How smart. :-)

**Review by justdave — APPROVED** [review]
Apparently so. Looks good! Thanks!

**Pull request merged**
