### PR TITLE
[5.2] Bug 1888068: Run development copy in Docker

### PR DESCRIPTION
**Pull request by justdave**
Here's a Docker config that'll run a development copy (with cheap default user/pass on everything) in Docker.  Much less complicated than harmony. ;-)

default admin user/pass can be found in docker/checksetup_answers.txt

`docker-compose up` will build and run it.
http://127.0.0.1:8080/ to access it once it's running.

### CODE REVIEW

**Comment by kaihendry** [comment]
Just for comparison here's the Dockerfile I used with Bugzilla years back https://github.com/unee-t/bugzilla/blob/master/Dockerfile

* https://github.com/unee-t/bugzilla-customisation/blob/master/Dockerfile
* https://github.com/unee-t/bugzilla-customisation/blob/master/docker-compose.yml

**Comment by Mrbibi38** [comment]
Hello, i have an issue. 
I clone this branch of the repositories and execute the commande **docker compose up**.
Everything building up but when it's done i have an Internal error when i want to acces to page http://ADRESSE-OF-MY-SERVER/8080.

In the log error file of the web container if have this :
```
[Fri May 06 13:55:55.319127 2022] [mpm_prefork:notice] [pid 18] AH00163: Apache/2.4.41 (Ubuntu) mod_perl/2.0.11 Perl/v5.30.0 configured -- resuming normal operations
[Fri May 06 13:55:55.319220 2022] [core:notice] [pid 18] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 06 13:56:15.372986 2022] [perl:error] [pid 28] [client 192.168.0.200:50197] The /var/www/html/data/params.json file does not exist. You probably need to run checksetup.pl. at /var/www/html/Bugzilla/Config.pm line 341.\n
[Fri May  6 13:56:15 2022] (28) Apache2::SizeLimit httpd process too big, exiting at SIZE=115792 KB SHARE=5988 KB UNSHARED=109804 REQUESTS=2 LIFETIME=0 seconds
[Fri May  6 13:56:15 2022] (29) Apache2::SizeLimit httpd process too big, exiting at SIZE=115624 KB SHARE=4940 KB UNSHARED=110684 REQUESTS=2 LIFETIME=0 seconds
[Fri May 06 13:57:21.774657 2022] [perl:error] [pid 30] [client 192.168.0.200:50210] The /var/www/html/data/params.json file does not exist. You probably need to run checksetup.pl. at /var/www/html/Bugzilla/Config.pm line 341.\n
[Fri May  6 13:57:21 2022] (30) Apache2::SizeLimit httpd process too big, exiting at SIZE=115792 KB SHARE=5988 KB UNSHARED=109804 REQUESTS=2 LIFETIME=0 seconds
```
 
Anyone could help me ?

**Comment by justdave** [comment]
> Hello, I have an issue. I clone this branch of the repositories and execute the commande **docker compose up**. Everything building up but when it's done i have an **Internal error** when I want to acces to page http://ADRESSE-OF-MY-SERVER/8080.

I am unable to replicate this.  Also checking just in case you had a typo, it should be :8080 not /8080 on the end of the URL.

**Comment by justdave** [comment]
I just rebased the branch on top of the current 5.2 branch.

**Review by dylanwh — APPROVED** [review]

**Comment by mrenvoize** [comment]
All working here now for me, thanks for that last little push to get it over the line.

I'd love to see a small addition to the README to highlight this exists before it's merged ;)

Also, some guidance on expected usage, i.e some quick commands for those not all that familiar with bugzilla/docker on how to get into the container, restart things for testing changes etc as needed.

Those little hints would really help get prospective devs up to speed quicker.

**Comment by justdave** [comment]
I think this is ready to land now.

**Review by dylanwh — APPROVED** [review]

**Comment by mrenvoize** [comment]
This is great, it'll be a real help for aspiring Devs and those wanting to demo bugzilla locally before considering it for their use case.

**Pull request merged**
