### PR TITLE
[Bug 1851389] Update favicon with a modern buggie

### PR DESCRIPTION
**Pull request by hellcp**
There are two variants for 16, 24 and 32 px. The top ones are edge to edge, the bottom have a 1px border on the left and right to make them stand out from the background better. I wasn't sure which ones to use, so the current PR includes the top ones, closer to the older favicon, but I would love to know if you maybe like some from the bottom, I can swap them out easily at any point.
favicons

The larger favicon shows up pretty nicely in Firefox new page shortcuts, but actually having a full size logo there would require adding some tags, which are outside of the scope of this
Screenshot from 2022-09-04 14-35-28

### CODE REVIEW

**Comment by hellcp** [comment]
I prepared a few more options, to see some alternative colours we could use for the background. Click on them to see the full resolution, I didn't want to take up too much vertical space with them. Orange variant is called www, because I will most likely use it as a replacement for the current www.bugzilla.org favicon, and Purple is called intense because it's a more intense version of the one I did above. Cyan should probably be called Mint, and Mint should be called Grint, but it doesn't exactly matter.
|Pink|Red|Orange (www)|Yellow|Dark Green|Green|Cyan|Blue|Navy|Purple (Intense)|Gray|Mint|
|---|---|---|---|---|---|---|---|---|---|---|---|
|00-favicons-pink|01-favicons-red|02-favicons-www|03-favicons-yellow|04-favicons-darkgreen|05-favicons-green|06-favicons-cyan|07-favicons-blue|08-favicons-navy|09-favicons-intense|10-favicons-gray|11-favicons-mint|

In a way I kind of want to add an option to the admin panel to select one of those and include all of them, but that's probably out of the scope of this PR too.

**Comment by justdave** [comment]
Do we have a Bugzilla bug for this PR? Also, I think rebasing will fix the tests.

**Comment by hellcp** [comment]
I worked on this based on bmo#1241904, but that's for bmo, I should probably create an issue specifically for bugzilla, since the issue is the same, just the software is different

**Comment by hellcp** [comment]
Rebased the PR on the current 5.2 branch and created a [bug 1851389](https://bugzilla.mozilla.org/show_bug.cgi?id=1851389) for it

**Review by justdave — APPROVED** [review]
I like it.  Can we get this on Harmony, too?

**Pull request merged**
