### PR TITLE
[5.2] Bug 868869: Require MySQL 5.6, Bug 1467006: explicit MariaDB support

### PR DESCRIPTION
**Pull request by justdave**
* Require MySQL 5.6.12 for InnoDB Fulltext support
* ~~Blocklist MySQL 8+ for groups issue~~
* Independently require MariaDB 10+ for InnoDB fulltext support

~~See [Bug 1851354](https://bugzilla.mozilla.org/show_bug.cgi?id=1851354)~~
See [Bug 868869](https://bugzilla.mozilla.org/show_bug.cgi?id=868869)

### CODE REVIEW

**Comment by justdave** [comment]
Dylan reviewed a different version of this patch that was attached to the bug. The previous version did not have the MySQL version bump (which should have happened in version 5.0.5 and didn't) or the auto-detection of MariaDB.

**Review by dklawren — DISMISSED** [review]
I would prefer the working be changed from blacklisted to something more friendly such as disallowed or similar. Similar to how our new repos are using main now instead of master.

Also Frederic makes a good point about just requiring DBD::MariaDB for the mariadb feature. DBD::MariaDB is also more recently maintained.

**Review by dylanwh — DISMISSED** [review]

**Comment by bovine** [comment]
Should this be closed since a fix from #153 has been merged into 5.2 branch?

**Comment by justdave** [comment]
> Should this be closed since a fix from #153 has been merged into 5.2 branch?

Yes but...  some pieces of it need to get merged into #106 first.

**Comment by justdave** [comment]
Actually, the "require MySQL 5.6" part still needs to land, we just need to drop the "Blocklist MySQL 8" part.

**Comment by bovine** [comment]
The summary of [bug 1851354](https://bugzilla.mozilla.org/show_bug.cgi?id=1851354) still reads only "Blocklist MySQL 8.0 and newer in checksetup.pl"

**Comment by justdave** [comment]
Updated summary to point at [Bug 868869](https://bugzilla.mozilla.org/show_bug.cgi?id=868869) instead.

**Comment by justdave** [comment]
Moving this back to draft status for now, this needs changes in light of MySQL 8 support landing before this can land.

**Comment by justdave** [comment]
See also [bug 1467006](https://bugzilla.mozilla.org/show_bug.cgi?id=1467006)

**Review by dylanwh — APPROVED** [review]

**Pull request merged**
